lecture first: create buttons
js-tasks-ru/htmlcss-20230530_avksntv pull request #7
Opened 2023-06-08 00:58 UTC by avksntv

Цвета для дз лекций назначаем стандартно ведь? Или подключать mail.css и назначать переменные там или создавать у себя переменные в button.css?

2023-06-08 00:59 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-09 12:59 UTC, GSemikozov requested changes

2023-06-09 12:59 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +    <div buttons class="buttons">
верстаем не buttons, а button, соответственно заворачивать все кнопки в общий враппер и стилизовать их и делать зависимыми от этого враппера не надо

2023-06-09 12:59 UTC, GSemikozov commented on 03-lection1/01-button/index.html
> +      <button class="buttons__btn buttons__primary">Primary</button>
1. это .button
2. как пишем модификаторы? Верно, надо исправлять :)
3. и дальше - то же самое ниже

2023-06-09 12:59 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  width: 189px;
ширину не нужно ограничивать

2023-06-09 12:59 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  display: flex;
делать кнопку блочной не надо, если хочется использовать флекс, тогда - inline-flex

2023-06-09 12:59 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  padding: 15px 0px 14px 0px;
слева-справа паддинги тоже нужны (можно 15px)

2023-06-09 12:59 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  margin-right: 33px;
марджины на уровне блока не задаем

2023-06-09 12:59 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  transition: background-color 1s;
транзишны пока не надо

2023-06-09 12:59 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.buttons__primary_disabled {
это состояние будет общим для всех типов кнопок - .button:disabled

2023-06-09 12:59 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  opacity: 0.5;
не хватает pointer-events: none

2023-06-10 07:52 UTC, avksntv commented
Почти переписал все полностью. Надеюсь я правильно понял после пятничной лекции. Мне кажется мы все думали, что верстка должна быть 1 в 1 с макетом. )) Про будущее не задумывались.

2023-06-11 20:03 UTC, GSemikozov requested changes

2023-06-11 20:03 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +  padding: 15px;
в таком варианте высота кнопки будет 49, а надо 28. Поэтому - либо паддинги укажем как в макете, либо - ограничим высоту height: 48px

2023-06-12 01:26 UTC, avksntv commented
Добавил height

2023-06-12 19:51 UTC, GSemikozov approved these changes

2023-06-12 19:51 UTC, merged